/* Repository touch marker. */
import { CfoBudgetBar, CfoExecution } from "./CfoExecution.tsx";
import type { CfoResult } from "../../shared/voiceCfo.ts";
import { useMemo, useState } from "react";
import { ArrowDownRight, ArrowUpRight, Bell, Download, Plus, Settings2, Sparkles, Target, TrendingUp, Wallet, Pencil, Check } from "lucide-react";
import type { AppState } from "../types/finance.ts";
import { CATEGORIES, type Category } from "../../shared/categories.ts";
import { inr, planningAlerts, type Goal, type CoachReport } from "../../shared/planning.ts";
import { displayText } from "../../shared/branding.ts";
import { api } from "../lib/api.ts";
import { FinanceDialog } from "./FinanceDialog.tsx";

import { adaptiveMetrics } from "../../shared/memory.ts";
import { AgentMemoryPanel, BudgetForecast, GoalForecast } from "./AdaptiveMemory.tsx";

type FormState = { mode: "goal" | "budget" | "allocate"; revision: number; goal?: Goal; category: Category; limit: number };
export function GoalsView({ state, onSave, onPreferences, cfo, onCfoClear }: {onCfoClear: () => void; cfo?: CfoResult | null; state: AppState; onSave: (body: unknown) => Promise<void>; onPreferences: () => void }) {
  const plan = state.planning!;
  const asOf = state.dataDate!;
  const metrics = useMemo(() => adaptiveMetrics(state.transactions, plan, asOf), [state.transactions, plan, asOf]);
  const alerts = useMemo(() => planningAlerts(state.transactions, plan, asOf, state.subscriptions), [state.transactions, plan, asOf, state.subscriptions]);
  const [form, setForm] = useState<FormState | null>(null);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const [coachBusy, setCoachBusy] = useState(false);
  const [coach, setCoach] = useState<{ report: CoachReport; signature: string } | null>(null);
  const signature = `${state.syncedAt}:${state.transactions.length}:${plan.revision}:${metrics.month.expense}:${metrics.month.income}`;
  const report = coach?.signature === signature ? coach.report : undefined;
  const commit = async (body: unknown) => { setBusy(true); setError(""); try { await onSave(body); } catch (e) { setError(displayText((e as Error).message)); throw e; } finally { setBusy(false); } };
  const applyRecommendation = (body: Record<string, unknown>) => { void commit({ ...body, revision: plan.revision }).catch(() => {}); };
  const openGoal = (goal?: Goal) => setForm({ mode: "goal", revision: plan.revision, goal, category: "personal", limit: 10000 });
  const generate = async () => { setCoachBusy(true); setError(""); try { setCoach({ report: await api<CoachReport>("/planning/coach", {}), signature }); } catch (e) { setError(displayText((e as Error).message)); } finally { setCoachBusy(false); } };
  const download = async () => { try { const { buildPlanningPdf } = await import("../lib/planningPdf.ts"); buildPlanningPdf(state, report).save(`LedgerLens-Financial-Plan-${asOf}.pdf`); } catch { setError("The report could not be generated. Please try again."); } };
  return <div className="finance-shell finance-page">
    <header className="finance-page-heading"><div><div className="finance-eyebrow">YOUR MONEY, WITH DIRECTION</div><h1>Goals & budgets<span className="heading-dot">.</span></h1><p>Turn everyday decisions into the life you’re planning.</p></div><div className="finance-actions"><button className="finance-button" onClick={onPreferences}><Settings2 size={15} /> Preferences</button><button className="finance-button" onClick={() => void download()}><Download size={15} /> Export report</button></div></header>
    {error && <p className="finance-alert critical" role="alert">{displayText(error)}</p>}
    {cfo?.kind === 'rebalance' && !cfo.shortfall && <div className="cfo-highlight" style={{borderRadius:18, marginBottom:24}}>
      <CfoExecution result={cfo} onClear={onCfoClear} />
      {cfo.id.startsWith('stage-') && <section className="finance-card" style={{padding:24}} aria-label="Stage rebalance plan">
        <p>Stage scenario · illustrative starting budgets · ₹12,000 reserved for medical expenses</p>
        <strong>🔒 Emergency Fund — PROTECTED BY CONSTRAINT</strong>
        <h2>New Safe Daily Spend: ₹1,420/day</h2>
        {cfo.rebalanceActions.map(a=><div key={a.name} style={{marginTop:16}}><strong>{a.name}: {inr(a.before)} → {inr(a.after)}</strong><div className="finance-progress"><CfoBudgetBar spent={a.after} limit={a.before} before={a.after} commandId={cfo.id} /></div><small>{inr(-a.amount)} shifted to medical reserve</small></div>)}
      </section>}
    </div>}
    <section className="finance-overview"><div className="finance-safe"><div className="finance-eyebrow"><span className="live-dot" /> {displayText(plan.profile.name)} · THROUGH {asOf}</div><div className="safe-label">{metrics.usesIncomeTargetFallback ? "Estimated daily planning allowance" : "Your daily safe-to-spend"}</div><div className="safe-amount">{inr(metrics.safeToSpend)}<span>/ day</span></div><p>After reserving {plan.profile.savingsTargetPct}% of your income target for savings.<br />{metrics.usesIncomeTargetFallback ? "Provisional: based on your income target; no income received in this statement month." : "Uses received income, capped at your target, less planned allocations."} Your daily advisory limit also applies.</p><div className="safe-footer"><span><Wallet size={14} /> Income target {inr(plan.profile.monthlyIncomeTarget)}</span><span>Statement month · {asOf.slice(0, 7)}</span></div></div><div className="finance-health"><div className="health-ring" style={{ background: `conic-gradient(var(--finance-mint) ${metrics.score}%, var(--finance-line) 0)` }}><div><strong>{metrics.score}</strong><span>/ 100</span></div></div><h2>Savings health</h2><p>{metrics.score >= 75 ? "Strong foundations. Keep the momentum." : metrics.score >= 40 ? "Building momentum. A little consistency goes far." : "Time to reset. Start with one spending limit."}</p><small>Based on savings target coverage and budgets.</small></div></section>
    <section className="finance-stats">{[
      { label: "Monthly income", value: inr(metrics.month.income), hint: "Money received this statement month", icon: ArrowDownRight, tone: "mint" },
      { label: "Monthly expenses", value: inr(metrics.month.expense), hint: "Excludes internal transfers", icon: ArrowUpRight, tone: "rose" },
      { label: "Net savings", value: inr(metrics.month.savings), hint: "Income less expenses", icon: Wallet, tone: "blue" },
      { label: "Savings rate", value: `${metrics.savingsRate.toFixed(1)}%`, hint: `Your target is ${plan.profile.savingsTargetPct}%`, icon: TrendingUp, tone: "violet" },
    ].map(({ label, value, hint, icon: Icon, tone }) => <article key={label} className={`finance-card finance-stat ${tone}`}><div><span>{label}</span><Icon size={16} /></div><strong>{value}</strong><p>{hint}</p></article>)}</section>

    <section className="finance-section"><div className="finance-section-title"><div><div className="finance-eyebrow">01 / THE BIGGER PICTURE</div><h2>Make room for what matters</h2></div><button className="finance-button primary" onClick={() => openGoal()}><Plus size={16} /> New goal</button></div>
      {plan.starterPlan && <div className="finance-starter"><Sparkles size={16} /><p><strong>A starter plan to explore.</strong> Goal balances are illustrative, not verified bank savings. Edit them or start from zero. Allocations record a plan; they do not move money.</p><button disabled={busy} onClick={() => void commit({ action: "clear-sample-balances", revision: plan.revision }).catch(() => {})}>Start from zero</button></div>}
      <div className="finance-goal-grid">{metrics.goals.map(goal => <article className={`finance-card goal-card ${goal.color} ${cfo?.protectedGoals.includes(goal.id) && cfo.kind === "rebalance" ? "cfo-protected" : ""} ${cfo?.goalSimulation?.goalId === goal.id ? "cfo-highlight" : ""}`} key={goal.id}><div className="goal-top"><span className="goal-icon"><Target size={19} /></span><span className="finance-tag">{goal.percent >= 100 ? "ACHIEVED" : goal.overdue ? "REVISE DATE" : `${goal.daysLeft} DAYS TO GO`}</span><button className="finance-icon-button" onClick={() => openGoal(goal)} aria-label={`Edit ${goal.name}`}><Pencil size={14} /></button></div><h3>{displayText(goal.name)}</h3><div className="goal-amount">{inr(goal.saved)} <span>of {inr(goal.target)}</span></div><div className="finance-progress" role="progressbar" aria-label={goal.name} aria-valuenow={Math.round(goal.percent)} aria-valuemin={0} aria-valuemax={100}><span style={{ width: `${goal.percent}%` }} /></div><div className="goal-progress-label"><span>{goal.percent.toFixed(0)}% complete</span><span>{goal.targetDate}</span></div><p className="goal-recommendation"><Sparkles size={13} />{goal.remaining ? `Set aside ${inr(goal.monthlyNeeded)}/month to close the gap.` : "You’ve reached this milestone. Set your next goal."}</p><GoalForecast goal={goal} metrics={metrics} learning={state.memory?.learningUpdates[0]} busy={busy} onApply={applyRecommendation} /><div className="goal-actions"><button disabled={busy || !goal.remaining} className="finance-button" onClick={() => void commit({ action: "allocate", revision: plan.revision, id: goal.id, amount: Math.min(1000, goal.remaining) }).catch(() => {})}>{goal.remaining ? <Plus size={13} /> : <Check size={13} />}{goal.remaining ? `Allocate ${inr(Math.min(1000, goal.remaining))}` : "Goal complete"}</button><button className="finance-text-button" disabled={!goal.remaining} onClick={() => setForm({ mode: "allocate", revision: plan.revision, goal, category: "personal", limit: 10000 })}>Custom amount</button></div></article>)}</div>
    </section>

    <div className="finance-budget-layout"><section className="finance-card budget-section"><div className="finance-section-title"><div><div className="finance-eyebrow">02 / EVERYDAY INTENTION</div><h2>Budgets that keep you on track</h2></div><button className="finance-icon-button" aria-label="Add category budget" onClick={() => setForm({ mode: "budget", revision: plan.revision, category: "personal", limit: 10000 })}><Plus size={20} /></button></div><p className="finance-hint">{metrics.monthStart} – {asOf} · Amber at 80% · Red at 100%</p><div className="budget-list">{metrics.budgets.map(b => <div className={`budget-row ${cfo?.highlightCategories.includes(b.category) ? "cfo-highlight" : ""} ${b.percent >= 100 ? "over" : b.percent >= 80 ? "near" : ""}`} key={b.category}><div className="budget-row-top"><strong>{b.name}</strong><button className="finance-text-button" onClick={() => setForm({ mode: "budget", revision: plan.revision, category: b.category, limit: b.limit })} aria-label={`Edit ${b.name} budget`}>{inr(b.spent)} <span>/ {inr(b.limit)}</span> <Pencil size={12} /></button></div><div className="finance-progress"><CfoBudgetBar spent={b.spent} limit={b.limit} before={cfo?.id.startsWith("stage-") ? undefined : cfo?.rebalanceActions.find(a => a.category === b.category)?.before} commandId={cfo?.id} /></div><div className="budget-row-bottom"><span>{b.percent >= 100 ? `${inr(b.spent - b.limit)} over budget` : `${inr(b.remaining)} left to spend`}</span><span>{b.percent.toFixed(0)}% used</span></div><BudgetForecast budget={b} metrics={metrics} busy={busy} onApply={applyRecommendation} /></div>)}</div><button className="finance-button" onClick={() => setForm({ mode: "budget", revision: plan.revision, category: "other_expense", limit: 10000 })}><Plus size={14} /> Set a category budget</button></section>
    <aside className="finance-card finance-alert-panel"><div className="finance-section-title"><div><div className="finance-eyebrow">03 / A GENTLE HEADS-UP</div><h2>Keep an eye on these</h2></div><Bell size={19} /></div><p className="finance-hint">Your thresholds · {plan.profile.alertThresholds.join(" / ")}%</p><div className="finance-alert-list">{alerts.length ? alerts.map(alert => <article className={`finance-alert ${alert.severity}`} key={alert.id}><strong>{alert.title}</strong><p>{displayText(alert.detail)}</p></article>) : <div className="finance-empty"><Check size={26} /><strong>You’re all caught up.</strong><p>No alerts for your current preferences.</p></div>}</div><button className="finance-text-button" onClick={onPreferences}>Customize your alerts <ArrowUpRight size={14} /></button></aside></div>

    <AgentMemoryPanel memory={state.memory} metrics={metrics} busy={busy} onApply={applyRecommendation} />
    <section className="finance-card finance-coach"><div className="finance-section-title"><div><div className="finance-eyebrow">04 / SEE THE PATTERN</div><h2><Sparkles size={22} /> Your financial coach</h2></div><button disabled={coachBusy} className="finance-button primary" onClick={() => void generate()}><Sparkles size={15} />{coachBusy ? "Synthesizing insights…" : "Generate AI report"}</button></div><div className="coach-summary-grid"><article><span>LAST SEVEN DAYS</span><strong>{inr(metrics.week.expense)} <small>spent</small></strong><p>{inr(metrics.week.income)} received · {inr(metrics.week.savings)} net</p><p>{metrics.weekStart} – {asOf}</p></article><article><span>MONTH TO DATE</span><strong>{inr(metrics.month.savings)} <small>net</small></strong><p>{inr(metrics.month.income)} received · {inr(metrics.month.expense)} spent</p><p>{metrics.monthStart} – {asOf}</p></article><article><span>MONTH-END CASH FLOW ESTIMATE</span><strong>{inr(metrics.projectedNet)}</strong><p>Assumes the recorded daily pace continues.</p><p>A projection, not a guaranteed balance.</p></article></div>
      {report ? <div className="coach-narrative"><span className="finance-tag">{report.source} · {new Date(report.generatedAt).toLocaleTimeString()}</span><p>{displayText(report.summary)}</p>{report.warning && <p className="finance-hint">{report.warning}</p>}</div> : <p className="finance-hint">{coach ? "Your ledger or plan changed. Generate a fresh AI report; the calculations below are already current." : "Insights below are calculated from your ledger. Generate an AI report for a personalized narrative."}</p>}
      <div className="coach-recommendations">{(report?.recommendations ?? metrics.recommendations).map((text, i) => <article key={i}><span>{String(i + 1).padStart(2, "0")}</span><p>{displayText(text)}</p></article>)}</div>
    </section><footer className="finance-page-footer">Statement-based planning · {state.importedTransactionCount ?? state.transactions.length} imported records + {state.liveTransactionCount ?? 0} live entries · Amounts in INR</footer>
    {form && <FinanceDialog title={form.mode === "budget" ? "Set a monthly budget" : form.mode === "allocate" ? `Allocate to ${displayText(form.goal!.name)}` : form.goal ? "Edit financial goal" : "Create a financial goal"} onClose={() => setForm(null)}><form onSubmit={async e => { e.preventDefault(); const data = new FormData(e.currentTarget); const body = form.mode === "budget" ? { category: data.get("category"), limit: Number(data.get("limit")) } : form.mode === "allocate" ? { id: form.goal!.id, amount: Number(data.get("amount")) } : { id: form.goal?.id, name: data.get("name"), target: Number(data.get("target")), saved: Number(data.get("saved")), targetDate: data.get("targetDate") }; try { await commit({ action: form.mode, revision: form.revision, ...body }); setForm(null); } catch { /* Keep entered values available for correction. */ } }}>
      {form.mode === "budget" ? <><label>Expense category<select name="category" defaultValue={form.category}>{Object.entries(CATEGORIES).filter(([id]) => !["internal_transfer", "customer_receipt", "other_income", "gateway_settlement"].includes(id)).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><label>Monthly limit (₹)<input name="limit" type="number" min="0.01" step="0.01" required defaultValue={form.limit} /></label></> : form.mode === "allocate" ? <><p className="finance-hint">Record a savings allocation. This does not initiate a bank transfer.</p><label>Amount (₹)<input name="amount" type="number" min="0.01" max={form.goal!.target - form.goal!.saved} step="0.01" required defaultValue={Math.min(1000, form.goal!.target - form.goal!.saved)} /></label></> : <><label>What are you saving for?<input name="name" required maxLength={60} defaultValue={form.goal?.name} placeholder="A place of my own" /></label><div className="finance-form-grid"><label>Target amount (₹)<input name="target" type="number" min="0.01" step="0.01" required defaultValue={form.goal?.target ?? 100000} /></label><label>Already saved (₹)<input name="saved" type="number" min="0" step="0.01" required defaultValue={form.goal?.saved ?? 0} /></label></div><label>Target date<input name="targetDate" type="date" required defaultValue={form.goal?.targetDate ?? `${Number(asOf.slice(0, 4)) + 1}-${asOf.slice(5)}`} /></label><p className="finance-hint">Use your actual savings balance. This is a planning record, not a bank balance.</p></>}
      {error && <p role="alert" className="finance-error">{displayText(error)}</p>}<button className="finance-button primary" disabled={busy}>{busy ? "Saving…" : "Save to my plan"}</button>
    </form></FinanceDialog>}
  </div>;
}
